# Generated by Django 6.0.6 on 2026-06-17 09:37

import django.db.models.deletion
import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('worker_fee_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='labor_charges_pkr',
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='verified_technician_name',
            field=models.CharField(default='', help_text='Customer confirms the name of the technician', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='otp_code',
            field=models.CharField(default=invoices.models.generate_otp, max_length=6),
        ),
        migrations.AddField(
            model_name='invoice',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_fee_at_time_pkr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='invoices.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.servicetype')),
            ],
        ),
    ]
